# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gossip.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gossip.proto',
  package='gossip_pb',
  syntax='proto3',
  serialized_pb=_b('\n\x0cgossip.proto\x12\tgossip_pb\"~\n\x07Request\x12\x35\n\x11\x61\x64\x64_build_request\x18\x01 \x01(\x0b\x32\x1a.gossip_pb.AddBuildRequest\x12<\n\x14registration_request\x18\x02 \x01(\x0b\x32\x1e.gossip_pb.RegistrationRequest\"\xa4\x01\n\x0f\x41\x64\x64\x42uildRequest\x12\x0c\n\x04sha1\x18\x01 \x01(\t\x12\x0c\n\x04node\x18\x02 \x01(\t\x12\r\n\x05uname\x18\x03 \x01(\t\x12\x11\n\ttoolchain\x18\x04 \x01(\t\x12\x10\n\x08revision\x18\x05 \x01(\t\x12\x12\n\nstart_time\x18\x06 \x01(\x04\x12\x10\n\x08\x65nd_time\x18\x07 \x01(\x04\x12\x0b\n\x03log\x18\x08 \x01(\t\x12\x0e\n\x06status\x18\t \x01(\r\"/\n\x13RegistrationRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\rb\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='gossip_pb.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='add_build_request', full_name='gossip_pb.Request.add_build_request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='registration_request', full_name='gossip_pb.Request.registration_request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=153,
)


_ADDBUILDREQUEST = _descriptor.Descriptor(
  name='AddBuildRequest',
  full_name='gossip_pb.AddBuildRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sha1', full_name='gossip_pb.AddBuildRequest.sha1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node', full_name='gossip_pb.AddBuildRequest.node', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uname', full_name='gossip_pb.AddBuildRequest.uname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toolchain', full_name='gossip_pb.AddBuildRequest.toolchain', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='revision', full_name='gossip_pb.AddBuildRequest.revision', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='gossip_pb.AddBuildRequest.start_time', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='gossip_pb.AddBuildRequest.end_time', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log', full_name='gossip_pb.AddBuildRequest.log', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='gossip_pb.AddBuildRequest.status', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=320,
)


_REGISTRATIONREQUEST = _descriptor.Descriptor(
  name='RegistrationRequest',
  full_name='gossip_pb.RegistrationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='gossip_pb.RegistrationRequest.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='gossip_pb.RegistrationRequest.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=369,
)

_REQUEST.fields_by_name['add_build_request'].message_type = _ADDBUILDREQUEST
_REQUEST.fields_by_name['registration_request'].message_type = _REGISTRATIONREQUEST
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['AddBuildRequest'] = _ADDBUILDREQUEST
DESCRIPTOR.message_types_by_name['RegistrationRequest'] = _REGISTRATIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'gossip_pb2'
  # @@protoc_insertion_point(class_scope:gossip_pb.Request)
  ))
_sym_db.RegisterMessage(Request)

AddBuildRequest = _reflection.GeneratedProtocolMessageType('AddBuildRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDBUILDREQUEST,
  __module__ = 'gossip_pb2'
  # @@protoc_insertion_point(class_scope:gossip_pb.AddBuildRequest)
  ))
_sym_db.RegisterMessage(AddBuildRequest)

RegistrationRequest = _reflection.GeneratedProtocolMessageType('RegistrationRequest', (_message.Message,), dict(
  DESCRIPTOR = _REGISTRATIONREQUEST,
  __module__ = 'gossip_pb2'
  # @@protoc_insertion_point(class_scope:gossip_pb.RegistrationRequest)
  ))
_sym_db.RegisterMessage(RegistrationRequest)


# @@protoc_insertion_point(module_scope)
